include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    prefer_final_locals: true
    require_trailing_commas: true
    prefer_final_in_for_each: true
    prefer_final_fields: true
    unawaited_futures: true
    unnecessary_await_in_return: true

analyzer:
  exclude:
    - "lib/gen/*"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  plugins:
    - custom_lint