name: team_score
description: Score tracking app for teams

publish_to: 'none'
version: 1.2.1+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_hooks: ^0.20.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  firebase_core: ^3.0.0
  logger: ^2.3.0
  intl: ^0.19.0
  network_info_plus: ^5.0.3
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.1.1
  flutter_tts: ^4.0.2
  hooks_riverpod: ^2.4.3
  wakelock_plus: ^1.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.10
  custom_lint: ^0.6.4
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  pigeon: ^18.0.1
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true