name: team_score
description: Score tracking app for teams

publish_to: 'none'
version: 1.2.1+5

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_hooks: ^0.20.2
  flutter_riverpod: ^2.4.1
  riverpod_annotation: ^2.1.6
  freezed_annotation: ^2.4.1
  firebase_core: ^2.16.0
  logger: ^2.0.2
  intl: ^0.18.1
  network_info_plus: ^5.0.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.4.1
  flutter_tts: ^3.8.3
  hooks_riverpod: ^2.4.3
  wakelock_plus: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  build_runner: ^2.4.6
  custom_lint: ^0.5.3
  riverpod_generator: ^2.3.3
  riverpod_lint: ^2.1.1
  pigeon: ^12.0.0
  freezed: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true