name: team_score
description: Score tracking app for teams

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  flutter_hooks: ^0.20.0
  flutter_riverpod: ^2.3.9
  riverpod_annotation: ^2.1.2
  freezed_annotation: ^2.4.1
  firebase_core: ^2.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  custom_lint: ^0.5.2
  riverpod_generator: ^2.2.6
  riverpod_lint: ^2.0.2
  pigeon: ^10.1.6
  freezed: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true