// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrutmukso6WBK6-kZc0cZsto9Ov2kLAZU',
    appId: '1:830434320277:web:58ea722f4071a65856e09c',
    messagingSenderId: '830434320277',
    projectId: 'teamscore-1ae58',
    authDomain: 'teamscore-1ae58.firebaseapp.com',
    storageBucket: 'teamscore-1ae58.appspot.com',
    measurementId: 'G-1N162FNYNM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi79eUHGpwZ814N_pn5iU7wD1KA7FKEMU',
    appId: '1:830434320277:android:8429e2d6a5dd326156e09c',
    messagingSenderId: '830434320277',
    projectId: 'teamscore-1ae58',
    storageBucket: 'teamscore-1ae58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV61dd99zvlVpQgGjjA9bEQFMWfUBIVFo',
    appId: '1:830434320277:ios:a6520b78d451f29056e09c',
    messagingSenderId: '830434320277',
    projectId: 'teamscore-1ae58',
    storageBucket: 'teamscore-1ae58.appspot.com',
    iosClientId: '830434320277-i780i01vk8a1h108ugbt2n5a6ucdtbvf.apps.googleusercontent.com',
    iosBundleId: 'com.doozyx.teamScore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV61dd99zvlVpQgGjjA9bEQFMWfUBIVFo',
    appId: '1:830434320277:ios:93e311d1ec1f684756e09c',
    messagingSenderId: '830434320277',
    projectId: 'teamscore-1ae58',
    storageBucket: 'teamscore-1ae58.appspot.com',
    iosClientId: '830434320277-0c86orkifd5kul7h76rph34jva4kfagm.apps.googleusercontent.com',
    iosBundleId: 'com.doozyx.teamScore.RunnerTests',
  );
}
