// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'score_model.freezed.dart';

@freezed
class ScoreModel with _$ScoreModel {
  const factory ScoreModel({
    required int team1Score,
    required int team2Score,
  }) = _ScoreModel;

  factory ScoreModel.initial() => const ScoreModel(
        team1Score: 0,
        team2Score: 0,
      );
}
