name: Flutter Format, Analyze and Tests

on: [push]

jobs:
  analysis:
    name: check format,analyze and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Initialize Flutter
        uses: ./.github/actions/initialize-flutter
      - name: Check Code Format
        run: dart format . --set-exit-if-changed
      - name: Analyze code
        run: dart analyze . --fatal-infos --fatal-warnings
      - name: Run tests
        run: flutter test
